controller_joint_names: ['', 'right_hip_pitch', 'right_hip_yaw', 'right_hip_roll', 'right_knee_pitch', 'right_ankle_pitch', 'left_hip_pitch', 'left_hip_yaw', 'left_hip_roll', 'left_knee_pitch', 'left_ankle_pitch', ]
